# Generated by Django 4.0.4 on 2022-04-15 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movie.genres'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(help_text='Use only year', validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
